language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy scipy pandas nose
  - source activate test-env
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; 
        then 2to3 -nw splot/ > /dev/null; 
    fi

install:
  - conda install --yes pip
  - conda install --yes -c conda-forge --file requirements.txt
  # We need geopandas master, the legend_kwds is not in 0.3.0
  - conda install --yes -c conda-forge/label/dev geopandas
  - pip install libpysal
  # Pysal still needed for code not yet moved to libpysal
  - pip install pysal
  - pip install esda
  - pip install mapclassify
  - pip install -r requirements_dev.txt
  # Now install splot (don't use 'pip install .', we'll run out of space)
  - python setup.py sdist
  - cd dist && pip install splot-*.tar.gz && cd ..
  # We need the Agg backend to use Matplotlib on TravisCI, otherwise
  # we get an error "DISPLAY variable not set"
  - cp utils/matplotlibrc .


script:
  - nosetests splot
#  - cd notebooks
#  - make test

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
        on_change: always
        on_failure: always

after_success:
  - coveralls
